---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
    microservice: '{{ microservice }}'
    port: '{{ port }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u Poojamn110729@gmail.com -p Admin@123456 trial2q496n.jfrog.io 
    
    - name: pull an image
      shell: docker pull trial2q496n.jfrog.io/cicd-docker/microservicebasedapp/{{ microservice }}:v1.0.{{ build_number }}

    - name: remove container
      shell: docker rm -f {{ microservice }}
        
    - name: create a application container
      shell: docker run -id --name {{ microservice }} -p {{ port }}:{{ port }} --network new-bridge-network hiqodenew.jfrog.io/cicd-docker/microservicebasedapp/{{ microservice }}:v1.0.{{ build_number }} 
 
